var annotated_dup =
[
    [ "doctest", null, [
      [ "detail", null, [
        [ "has_insertion_operator_impl", null, [
          [ "any_t", "structdoctest_1_1detail_1_1has__insertion__operator__impl_1_1any__t.html", "structdoctest_1_1detail_1_1has__insertion__operator__impl_1_1any__t" ],
          [ "has_insertion_operator", "structdoctest_1_1detail_1_1has__insertion__operator__impl_1_1has__insertion__operator.html", null ]
        ] ],
        [ "remove_reference", "structdoctest_1_1detail_1_1remove__reference.html", "structdoctest_1_1detail_1_1remove__reference" ],
        [ "remove_reference< T & >", "structdoctest_1_1detail_1_1remove__reference_3_01_t_01_6_01_4.html", "structdoctest_1_1detail_1_1remove__reference_3_01_t_01_6_01_4" ],
        [ "remove_reference< T && >", "structdoctest_1_1detail_1_1remove__reference_3_01_t_01_6_6_01_4.html", "structdoctest_1_1detail_1_1remove__reference_3_01_t_01_6_6_01_4" ],
        [ "remove_const", "structdoctest_1_1detail_1_1remove__const.html", "structdoctest_1_1detail_1_1remove__const" ],
        [ "remove_const< const T >", "structdoctest_1_1detail_1_1remove__const_3_01const_01_t_01_4.html", "structdoctest_1_1detail_1_1remove__const_3_01const_01_t_01_4" ],
        [ "deferred_false", "structdoctest_1_1detail_1_1deferred__false.html", null ],
        [ "has_insertion_operator", "structdoctest_1_1detail_1_1has__insertion__operator.html", null ],
        [ "StringMakerBase", "structdoctest_1_1detail_1_1_string_maker_base.html", null ],
        [ "StringMakerBase< true >", "structdoctest_1_1detail_1_1_string_maker_base_3_01true_01_4.html", null ],
        [ "TestFailureException", "structdoctest_1_1detail_1_1_test_failure_exception.html", null ],
        [ "Subcase", "structdoctest_1_1detail_1_1_subcase.html", "structdoctest_1_1detail_1_1_subcase" ],
        [ "Result", "structdoctest_1_1detail_1_1_result.html", "structdoctest_1_1detail_1_1_result" ],
        [ "ExpressionDecomposer", "structdoctest_1_1detail_1_1_expression_decomposer.html", "structdoctest_1_1detail_1_1_expression_decomposer" ],
        [ "TestSuite", "structdoctest_1_1detail_1_1_test_suite.html", "structdoctest_1_1detail_1_1_test_suite" ],
        [ "TestCase", "structdoctest_1_1detail_1_1_test_case.html", "structdoctest_1_1detail_1_1_test_case" ],
        [ "RelationalComparator", "structdoctest_1_1detail_1_1_relational_comparator.html", "structdoctest_1_1detail_1_1_relational_comparator" ],
        [ "ResultBuilder", "structdoctest_1_1detail_1_1_result_builder.html", "structdoctest_1_1detail_1_1_result_builder" ],
        [ "IExceptionTranslator", "structdoctest_1_1detail_1_1_i_exception_translator.html", "structdoctest_1_1detail_1_1_i_exception_translator" ],
        [ "ExceptionTranslator", "classdoctest_1_1detail_1_1_exception_translator.html", "classdoctest_1_1detail_1_1_exception_translator" ],
        [ "StringStreamBase", "structdoctest_1_1detail_1_1_string_stream_base.html", null ],
        [ "StringStreamBase< true >", "structdoctest_1_1detail_1_1_string_stream_base_3_01true_01_4.html", null ],
        [ "StringStream", "structdoctest_1_1detail_1_1_string_stream.html", null ],
        [ "ContextScopeBase", "classdoctest_1_1detail_1_1_context_scope_base.html", "classdoctest_1_1detail_1_1_context_scope_base" ],
        [ "ContextScope", "classdoctest_1_1detail_1_1_context_scope.html", "classdoctest_1_1detail_1_1_context_scope" ],
        [ "MessageBuilder", "structdoctest_1_1detail_1_1_message_builder.html", "structdoctest_1_1detail_1_1_message_builder" ]
      ] ],
      [ "String", "classdoctest_1_1_string.html", "classdoctest_1_1_string" ],
      [ "TestCaseData", "structdoctest_1_1_test_case_data.html", "structdoctest_1_1_test_case_data" ],
      [ "AssertData", "structdoctest_1_1_assert_data.html", "structdoctest_1_1_assert_data" ],
      [ "MessageData", "structdoctest_1_1_message_data.html", "structdoctest_1_1_message_data" ],
      [ "SubcaseSignature", "structdoctest_1_1_subcase_signature.html", "structdoctest_1_1_subcase_signature" ],
      [ "IContextScope", "structdoctest_1_1_i_context_scope.html", "structdoctest_1_1_i_context_scope" ],
      [ "ContextOptions", "structdoctest_1_1_context_options.html", "structdoctest_1_1_context_options" ],
      [ "StringMaker", "structdoctest_1_1_string_maker.html", null ],
      [ "StringMaker< T * >", "structdoctest_1_1_string_maker_3_01_t_01_5_01_4.html", null ],
      [ "StringMaker< R C::* >", "structdoctest_1_1_string_maker_3_01_r_01_c_1_1_5_01_4.html", null ],
      [ "Approx", "classdoctest_1_1_approx.html", "classdoctest_1_1_approx" ],
      [ "Context", "classdoctest_1_1_context.html", "classdoctest_1_1_context" ],
      [ "CurrentTestCaseStats", "structdoctest_1_1_current_test_case_stats.html", "structdoctest_1_1_current_test_case_stats" ],
      [ "TestCaseException", "structdoctest_1_1_test_case_exception.html", "structdoctest_1_1_test_case_exception" ],
      [ "TestRunStats", "structdoctest_1_1_test_run_stats.html", "structdoctest_1_1_test_run_stats" ],
      [ "QueryData", "structdoctest_1_1_query_data.html", "structdoctest_1_1_query_data" ],
      [ "IReporter", "structdoctest_1_1_i_reporter.html", "structdoctest_1_1_i_reporter" ]
    ] ],
    [ "Algorithm_Strassen", "class_algorithm___strassen.html", "class_algorithm___strassen" ],
    [ "basic_ostream", "classbasic__ostream.html", null ],
    [ "char_traits", "structchar__traits.html", null ],
    [ "Matrix", "class_matrix.html", "class_matrix" ],
    [ "MatrixException", "class_matrix_exception.html", "class_matrix_exception" ],
    [ "Multithreaded_Version", "class_multithreaded___version.html", "class_multithreaded___version" ],
    [ "Multithreaded_VersionException", "class_multithreaded___version_exception.html", "class_multithreaded___version_exception" ],
    [ "Serial_Version", "class_serial___version.html", "class_serial___version" ],
    [ "Serial_VersionException", "class_serial___version_exception.html", "class_serial___version_exception" ],
    [ "Simple_Timer", "class_simple___timer.html", "class_simple___timer" ],
    [ "tuple", "classtuple.html", null ]
];